#!/usr/bin/env python3
"""Generate mamego_driver.c: the drivers[] list for the chosen driver source files."""
import re, sys
out, files = sys.argv[1], sys.argv[2:]
names, parents = [], set()
for f in files:
    for m in re.finditer(r'^\s*GAMEX?\(\s*\d+\s*,\s*(\w+)\s*,\s*(\w+)\s*,', open(f, errors='replace').read(), re.M):
        names.append(m.group(1))
        parents.add(m.group(2))
# Clones whose parent lives in a driver file we do not build get a stub parent
# flagged NOT_A_DRIVER (like driver_0), so they run as stand-alone games.
missing = sorted(parents - set(names) - {'0'})
with open(out, 'w') as o:
    o.write('/* Generated by gen_drivers.py from: %s */\n#include "driver.h"\n\n' % ' '.join(files))
    o.write('struct GameDriver driver_0 = { __FILE__, 0, "", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };\n\n')
    for n in missing: o.write('struct GameDriver driver_%s = { __FILE__, 0, "%s", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };\n' % (n, n))
    if missing: o.write('\n')
    for n in names: o.write('extern const struct GameDriver driver_%s;\n' % n)
    o.write('\nconst struct GameDriver *drivers[] = {\n')
    for n in names: o.write('\t&driver_%s,\n' % n)
    o.write('\t0\n};\n')
print(len(names), 'drivers,', len(missing), 'stub parents')
