/* Generated by gen_drivers.py from: src/drivers/pacman.c src/drivers/circus.c src/drivers/exidy.c src/drivers/astrocde.c src/drivers/starfire.c src/drivers/victory.c src/drivers/1942.c src/drivers/1943.c src/drivers/galaga.c src/drivers/dkong.c src/drivers/galaxian.c src/drivers/frogger.c src/drivers/scramble.c src/drivers/aerofgt.c src/drivers/bloodbro.c src/drivers/neogeo.c src/drivers/neogeo_modern_games.inc */
#include "driver.h"

struct GameDriver driver_0 = { __FILE__, 0, "", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };

struct GameDriver driver_amidar = { __FILE__, 0, "amidar", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };
struct GameDriver driver_ckong = { __FILE__, 0, "ckong", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };

extern const struct GameDriver driver_pacman;
extern const struct GameDriver driver_pacmanjp;
extern const struct GameDriver driver_pacmanm;
extern const struct GameDriver driver_npacmod;
extern const struct GameDriver driver_pacmod;
extern const struct GameDriver driver_hangly;
extern const struct GameDriver driver_hangly2;
extern const struct GameDriver driver_puckman;
extern const struct GameDriver driver_pacheart;
extern const struct GameDriver driver_piranha;
extern const struct GameDriver driver_pacplus;
extern const struct GameDriver driver_mspacman;
extern const struct GameDriver driver_mspacatk;
extern const struct GameDriver driver_pacgal;
extern const struct GameDriver driver_crush;
extern const struct GameDriver driver_crush2;
extern const struct GameDriver driver_crush3;
extern const struct GameDriver driver_maketrax;
extern const struct GameDriver driver_mbrush;
extern const struct GameDriver driver_paintrlr;
extern const struct GameDriver driver_ponpoko;
extern const struct GameDriver driver_ponpokov;
extern const struct GameDriver driver_eyes;
extern const struct GameDriver driver_eyes2;
extern const struct GameDriver driver_mrtnt;
extern const struct GameDriver driver_lizwiz;
extern const struct GameDriver driver_theglob;
extern const struct GameDriver driver_beastf;
extern const struct GameDriver driver_dremshpr;
extern const struct GameDriver driver_vanvan;
extern const struct GameDriver driver_vanvans;
extern const struct GameDriver driver_alibaba;
extern const struct GameDriver driver_circus;
extern const struct GameDriver driver_robotbwl;
extern const struct GameDriver driver_crash;
extern const struct GameDriver driver_ripcord;
extern const struct GameDriver driver_sidetrac;
extern const struct GameDriver driver_targ;
extern const struct GameDriver driver_spectar;
extern const struct GameDriver driver_spectar1;
extern const struct GameDriver driver_mtrap;
extern const struct GameDriver driver_mtrap3;
extern const struct GameDriver driver_mtrap4;
extern const struct GameDriver driver_venture;
extern const struct GameDriver driver_venture2;
extern const struct GameDriver driver_venture4;
extern const struct GameDriver driver_pepper2;
extern const struct GameDriver driver_hardhat;
extern const struct GameDriver driver_fax;
extern const struct GameDriver driver_seawolf2;
extern const struct GameDriver driver_spacezap;
extern const struct GameDriver driver_ebases;
extern const struct GameDriver driver_wow;
extern const struct GameDriver driver_gorf;
extern const struct GameDriver driver_gorfpgm1;
extern const struct GameDriver driver_robby;
extern const struct GameDriver driver_profpac;
extern const struct GameDriver driver_starfire;
extern const struct GameDriver driver_fireone;
extern const struct GameDriver driver_victory;
extern const struct GameDriver driver_victorba;
extern const struct GameDriver driver_1942;
extern const struct GameDriver driver_1942a;
extern const struct GameDriver driver_1942b;
extern const struct GameDriver driver_1943;
extern const struct GameDriver driver_1943e;
extern const struct GameDriver driver_1943j;
extern const struct GameDriver driver_1943kai;
extern const struct GameDriver driver_galaga;
extern const struct GameDriver driver_galagamw;
extern const struct GameDriver driver_galagads;
extern const struct GameDriver driver_gallag;
extern const struct GameDriver driver_galagab2;
extern const struct GameDriver driver_galaga84;
extern const struct GameDriver driver_nebulbee;
extern const struct GameDriver driver_radarscp;
extern const struct GameDriver driver_dkong;
extern const struct GameDriver driver_dkongjp;
extern const struct GameDriver driver_dkongjpo;
extern const struct GameDriver driver_dkongjr;
extern const struct GameDriver driver_dkngjrjp;
extern const struct GameDriver driver_dkjrjp;
extern const struct GameDriver driver_dkjrbl;
extern const struct GameDriver driver_dkong3;
extern const struct GameDriver driver_dkong3j;
extern const struct GameDriver driver_hunchbkd;
extern const struct GameDriver driver_herbiedk;
extern const struct GameDriver driver_herocast;
extern const struct GameDriver driver_galaxian;
extern const struct GameDriver driver_galmidw;
extern const struct GameDriver driver_superg;
extern const struct GameDriver driver_galaxb;
extern const struct GameDriver driver_galapx;
extern const struct GameDriver driver_galap1;
extern const struct GameDriver driver_galap4;
extern const struct GameDriver driver_galturbo;
extern const struct GameDriver driver_swarm;
extern const struct GameDriver driver_zerotime;
extern const struct GameDriver driver_uniwars;
extern const struct GameDriver driver_gteikoku;
extern const struct GameDriver driver_spacbatt;
extern const struct GameDriver driver_warofbug;
extern const struct GameDriver driver_pacmanbl;
extern const struct GameDriver driver_devilfsg;
extern const struct GameDriver driver_zigzag;
extern const struct GameDriver driver_zigzag2;
extern const struct GameDriver driver_scramblb;
extern const struct GameDriver driver_jumpbug;
extern const struct GameDriver driver_jumpbugb;
extern const struct GameDriver driver_levers;
extern const struct GameDriver driver_azurian;
extern const struct GameDriver driver_checkman;
extern const struct GameDriver driver_checkmaj;
extern const struct GameDriver driver_streakng;
extern const struct GameDriver driver_mooncrst;
extern const struct GameDriver driver_mooncrsg;
extern const struct GameDriver driver_mooncrsb;
extern const struct GameDriver driver_mooncrs2;
extern const struct GameDriver driver_fantazia;
extern const struct GameDriver driver_eagle;
extern const struct GameDriver driver_eagle2;
extern const struct GameDriver driver_mooncrgx;
extern const struct GameDriver driver_moonqsr;
extern const struct GameDriver driver_moonal2;
extern const struct GameDriver driver_moonal2b;
extern const struct GameDriver driver_kingball;
extern const struct GameDriver driver_kingbalj;
extern const struct GameDriver driver_frogger;
extern const struct GameDriver driver_frogseg1;
extern const struct GameDriver driver_frogseg2;
extern const struct GameDriver driver_froggrmc;
extern const struct GameDriver driver_scramble;
extern const struct GameDriver driver_scrambls;
extern const struct GameDriver driver_atlantis;
extern const struct GameDriver driver_atlants2;
extern const struct GameDriver driver_theend;
extern const struct GameDriver driver_theends;
extern const struct GameDriver driver_froggers;
extern const struct GameDriver driver_amidars;
extern const struct GameDriver driver_triplep;
extern const struct GameDriver driver_knockout;
extern const struct GameDriver driver_mariner;
extern const struct GameDriver driver_800fath;
extern const struct GameDriver driver_ckongs;
extern const struct GameDriver driver_mars;
extern const struct GameDriver driver_devilfsh;
extern const struct GameDriver driver_newsin7;
extern const struct GameDriver driver_hotshock;
extern const struct GameDriver driver_hunchbks;
extern const struct GameDriver driver_pspikes;
extern const struct GameDriver driver_svolly91;
extern const struct GameDriver driver_karatblz;
extern const struct GameDriver driver_karatblu;
extern const struct GameDriver driver_spinlbrk;
extern const struct GameDriver driver_spinlbru;
extern const struct GameDriver driver_spinlbrj;
extern const struct GameDriver driver_turbofrc;
extern const struct GameDriver driver_aerofgt;
extern const struct GameDriver driver_aerofgtb;
extern const struct GameDriver driver_aerofgtc;
extern const struct GameDriver driver_sonicwi;
extern const struct GameDriver driver_bloodbro;
extern const struct GameDriver driver_weststry;
extern const struct GameDriver driver_neogeo;
extern const struct GameDriver driver_nam1975;
extern const struct GameDriver driver_bstars;
extern const struct GameDriver driver_tpgolf;
extern const struct GameDriver driver_mahretsu;
extern const struct GameDriver driver_ridhero;
extern const struct GameDriver driver_alpham2;
extern const struct GameDriver driver_cyberlip;
extern const struct GameDriver driver_superspy;
extern const struct GameDriver driver_mutnat;
extern const struct GameDriver driver_kotm;
extern const struct GameDriver driver_sengoku;
extern const struct GameDriver driver_sengokh;
extern const struct GameDriver driver_burningf;
extern const struct GameDriver driver_burningh;
extern const struct GameDriver driver_lbowling;
extern const struct GameDriver driver_gpilots;
extern const struct GameDriver driver_joyjoy;
extern const struct GameDriver driver_quizdais;
extern const struct GameDriver driver_lresort;
extern const struct GameDriver driver_eightman;
extern const struct GameDriver driver_legendos;
extern const struct GameDriver driver_2020bb;
extern const struct GameDriver driver_2020bbh;
extern const struct GameDriver driver_socbrawl;
extern const struct GameDriver driver_fatfury1;
extern const struct GameDriver driver_roboarmy;
extern const struct GameDriver driver_fbfrenzy;
extern const struct GameDriver driver_kotm2;
extern const struct GameDriver driver_sengoku2;
extern const struct GameDriver driver_bstars2;
extern const struct GameDriver driver_quizdai2;
extern const struct GameDriver driver_3countb;
extern const struct GameDriver driver_aof;
extern const struct GameDriver driver_samsho;
extern const struct GameDriver driver_tophuntr;
extern const struct GameDriver driver_fatfury2;
extern const struct GameDriver driver_ssideki;
extern const struct GameDriver driver_kof94;
extern const struct GameDriver driver_aof2;
extern const struct GameDriver driver_fatfursp;
extern const struct GameDriver driver_savagere;
extern const struct GameDriver driver_ssideki2;
extern const struct GameDriver driver_samsho2;
extern const struct GameDriver driver_fatfury3;
extern const struct GameDriver driver_ssideki3;
extern const struct GameDriver driver_kof95;
extern const struct GameDriver driver_samsho3;
extern const struct GameDriver driver_rbff1;
extern const struct GameDriver driver_aof3;
extern const struct GameDriver driver_kof96;
extern const struct GameDriver driver_ssideki4;
extern const struct GameDriver driver_kizuna;
extern const struct GameDriver driver_samsho4;
extern const struct GameDriver driver_rbffspec;
extern const struct GameDriver driver_kof97;
extern const struct GameDriver driver_lastblad;
extern const struct GameDriver driver_irrmaze;
extern const struct GameDriver driver_rbff2;
extern const struct GameDriver driver_mslug2;
extern const struct GameDriver driver_kof98;
extern const struct GameDriver driver_lastbld2;
extern const struct GameDriver driver_neocup98;
extern const struct GameDriver driver_mslugx;
extern const struct GameDriver driver_kof99;
extern const struct GameDriver driver_garou;
extern const struct GameDriver driver_maglord;
extern const struct GameDriver driver_maglordh;
extern const struct GameDriver driver_ncombat;
extern const struct GameDriver driver_bjourney;
extern const struct GameDriver driver_crsword;
extern const struct GameDriver driver_trally;
extern const struct GameDriver driver_ncommand;
extern const struct GameDriver driver_wh1;
extern const struct GameDriver driver_wh2;
extern const struct GameDriver driver_wh2j;
extern const struct GameDriver driver_aodk;
extern const struct GameDriver driver_whp;
extern const struct GameDriver driver_mosyougi;
extern const struct GameDriver driver_overtop;
extern const struct GameDriver driver_ninjamas;
extern const struct GameDriver driver_twinspri;
extern const struct GameDriver driver_janshin;
extern const struct GameDriver driver_pulstar;
extern const struct GameDriver driver_spinmast;
extern const struct GameDriver driver_wjammers;
extern const struct GameDriver driver_karnovr;
extern const struct GameDriver driver_strhoop;
extern const struct GameDriver driver_magdrop2;
extern const struct GameDriver driver_magdrop3;
extern const struct GameDriver driver_gururin;
extern const struct GameDriver driver_miexchng;
extern const struct GameDriver driver_panicbom;
extern const struct GameDriver driver_kabukikl;
extern const struct GameDriver driver_neobombe;
extern const struct GameDriver driver_minasan;
extern const struct GameDriver driver_bakatono;
extern const struct GameDriver driver_turfmast;
extern const struct GameDriver driver_mslug;
extern const struct GameDriver driver_zedblade;
extern const struct GameDriver driver_viewpoin;
extern const struct GameDriver driver_quizkof;
extern const struct GameDriver driver_stakwin;
extern const struct GameDriver driver_ragnagrd;
extern const struct GameDriver driver_pgoal;
extern const struct GameDriver driver_stakwin2;
extern const struct GameDriver driver_shocktro;
extern const struct GameDriver driver_shocktr2;
extern const struct GameDriver driver_galaxyfg;
extern const struct GameDriver driver_wakuwak7;
extern const struct GameDriver driver_pbobble;
extern const struct GameDriver driver_pbobbl2n;
extern const struct GameDriver driver_marukodq;
extern const struct GameDriver driver_doubledr;
extern const struct GameDriver driver_gowcaizr;
extern const struct GameDriver driver_sdodgeb;
extern const struct GameDriver driver_tws96;
extern const struct GameDriver driver_blazstar;
extern const struct GameDriver driver_fightfev;
extern const struct GameDriver driver_pspikes2;
extern const struct GameDriver driver_sonicwi2;
extern const struct GameDriver driver_sonicwi3;
extern const struct GameDriver driver_popbounc;
extern const struct GameDriver driver_androdun;
extern const struct GameDriver driver_puzzledp;
extern const struct GameDriver driver_neomrdo;
extern const struct GameDriver driver_goalx3;
extern const struct GameDriver driver_neodrift;
extern const struct GameDriver driver_breakers;
extern const struct GameDriver driver_puzzldpr;
extern const struct GameDriver driver_breakrev;
extern const struct GameDriver driver_flipshot;
extern const struct GameDriver driver_ctomaday;
extern const struct GameDriver driver_nam1975m;
extern const struct GameDriver driver_bstarsm;
extern const struct GameDriver driver_tpgolfm;
extern const struct GameDriver driver_mahretsum;
extern const struct GameDriver driver_maglordm;
extern const struct GameDriver driver_alpham2m;
extern const struct GameDriver driver_ncombatm;
extern const struct GameDriver driver_cyberlipm;
extern const struct GameDriver driver_superspym;
extern const struct GameDriver driver_mutnatm;
extern const struct GameDriver driver_kotmm;
extern const struct GameDriver driver_sengokum;
extern const struct GameDriver driver_burningfm;
extern const struct GameDriver driver_lbowlingm;
extern const struct GameDriver driver_gpilotsm;
extern const struct GameDriver driver_joyjoym;
extern const struct GameDriver driver_bjourneym;
extern const struct GameDriver driver_quizdaism;
extern const struct GameDriver driver_lresortm;
extern const struct GameDriver driver_eightmanm;
extern const struct GameDriver driver_legendosm;
extern const struct GameDriver driver_2020bbm;
extern const struct GameDriver driver_socbrawlm;
extern const struct GameDriver driver_roboarmym;
extern const struct GameDriver driver_fatfury1m;
extern const struct GameDriver driver_fbfrenzym;
extern const struct GameDriver driver_crswordm;
extern const struct GameDriver driver_trallym;
extern const struct GameDriver driver_bstars2m;
extern const struct GameDriver driver_quizdai2m;
extern const struct GameDriver driver_samshom;
extern const struct GameDriver driver_tophuntrm;
extern const struct GameDriver driver_androdunm;
extern const struct GameDriver driver_ncommandm;
extern const struct GameDriver driver_kof94m;
extern const struct GameDriver driver_aof2m;
extern const struct GameDriver driver_wh2m;
extern const struct GameDriver driver_fatfurspm;
extern const struct GameDriver driver_savagerem;
extern const struct GameDriver driver_fightfevm;
extern const struct GameDriver driver_ssideki2m;
extern const struct GameDriver driver_spinmastm;
extern const struct GameDriver driver_samsho2m;
extern const struct GameDriver driver_wh2jm;
extern const struct GameDriver driver_wjammersm;
extern const struct GameDriver driver_karnovrm;
extern const struct GameDriver driver_gururinm;
extern const struct GameDriver driver_pspikes2m;
extern const struct GameDriver driver_fatfury3m;
extern const struct GameDriver driver_b2b;
extern const struct GameDriver driver_panicbomm;
extern const struct GameDriver driver_aodkm;
extern const struct GameDriver driver_sonicwi2m;
extern const struct GameDriver driver_zedbladem;
extern const struct GameDriver driver_galaxyfgm;
extern const struct GameDriver driver_strhoopm;
extern const struct GameDriver driver_quizkofm;
extern const struct GameDriver driver_ssideki3m;
extern const struct GameDriver driver_doubledrm;
extern const struct GameDriver driver_kof95m;
extern const struct GameDriver driver_twsoc96;
extern const struct GameDriver driver_samsho3m;
extern const struct GameDriver driver_stakwinm;
extern const struct GameDriver driver_pulstarm;
extern const struct GameDriver driver_whpm;
extern const struct GameDriver driver_kabukiklm;
extern const struct GameDriver driver_neobombem;
extern const struct GameDriver driver_gowcaizrm;
extern const struct GameDriver driver_rbff1m;
extern const struct GameDriver driver_aof3m;
extern const struct GameDriver driver_sonicwi3m;
extern const struct GameDriver driver_turfmastm;
extern const struct GameDriver driver_mslugm;
extern const struct GameDriver driver_puzzledpm;
extern const struct GameDriver driver_moshougi;
extern const struct GameDriver driver_marukodqm;
extern const struct GameDriver driver_neomrdom;
extern const struct GameDriver driver_sdodgebm;
extern const struct GameDriver driver_goalx3m;
extern const struct GameDriver driver_overtopm;
extern const struct GameDriver driver_neodriftm;
extern const struct GameDriver driver_kof96m;
extern const struct GameDriver driver_ssideki4m;
extern const struct GameDriver driver_kizunam;
extern const struct GameDriver driver_ninjamasm;
extern const struct GameDriver driver_ragnagrdm;
extern const struct GameDriver driver_pgoalm;
extern const struct GameDriver driver_ironclad;
extern const struct GameDriver driver_magdrop2m;
extern const struct GameDriver driver_samsho4m;
extern const struct GameDriver driver_rbffspecm;
extern const struct GameDriver driver_twinsprim;
extern const struct GameDriver driver_wakuwak7m;
extern const struct GameDriver driver_stakwin2m;
extern const struct GameDriver driver_ghostlop;
extern const struct GameDriver driver_breakersm;
extern const struct GameDriver driver_miexchngm;
extern const struct GameDriver driver_kof97m;
extern const struct GameDriver driver_magdrop3m;
extern const struct GameDriver driver_lastbladm;
extern const struct GameDriver driver_puzzldprm;
extern const struct GameDriver driver_popbouncm;
extern const struct GameDriver driver_shocktrom;
extern const struct GameDriver driver_blazstarm;
extern const struct GameDriver driver_rbff2m;
extern const struct GameDriver driver_mslug2m;
extern const struct GameDriver driver_lastbld2m;
extern const struct GameDriver driver_neocup98m;
extern const struct GameDriver driver_breakrevm;
extern const struct GameDriver driver_shocktr2m;
extern const struct GameDriver driver_flipshotm;
extern const struct GameDriver driver_pbobbl2nm;
extern const struct GameDriver driver_ctomadaym;
extern const struct GameDriver driver_mslugxm;
extern const struct GameDriver driver_vliner;
extern const struct GameDriver driver_zintrckb;
extern const struct GameDriver driver_froman2b;
extern const struct GameDriver driver_crswd2bl;
extern const struct GameDriver driver_diggerma;
extern const struct GameDriver driver_lasthope;
extern const struct GameDriver driver_bstarsh;
extern const struct GameDriver driver_maglordhm;
extern const struct GameDriver driver_ncombath;
extern const struct GameDriver driver_kotmh;
extern const struct GameDriver driver_sengokuh;
extern const struct GameDriver driver_burningfh;
extern const struct GameDriver driver_gpilotsh;
extern const struct GameDriver driver_bjourneyh;
extern const struct GameDriver driver_quizdaisk;
extern const struct GameDriver driver_2020bba;
extern const struct GameDriver driver_socbrawlh;
extern const struct GameDriver driver_samshoh;
extern const struct GameDriver driver_tophuntrh;
extern const struct GameDriver driver_aof2a;
extern const struct GameDriver driver_wh2h;
extern const struct GameDriver driver_fatfurspa;
extern const struct GameDriver driver_fightfeva;
extern const struct GameDriver driver_samsho2k;
extern const struct GameDriver driver_samsho2ka;
extern const struct GameDriver driver_quizkofk;
extern const struct GameDriver driver_kof95a;
extern const struct GameDriver driver_kof95h;
extern const struct GameDriver driver_samsho3h;
extern const struct GameDriver driver_fswords;
extern const struct GameDriver driver_rbff1a;
extern const struct GameDriver driver_rbff1ka;
extern const struct GameDriver driver_rbff1k;
extern const struct GameDriver driver_aof3k;
extern const struct GameDriver driver_kof96a;
extern const struct GameDriver driver_kof96h;
extern const struct GameDriver driver_ironclado;
extern const struct GameDriver driver_samsho4k;
extern const struct GameDriver driver_rbffspeck;
extern const struct GameDriver driver_kof97h;
extern const struct GameDriver driver_kof97k;
extern const struct GameDriver driver_lastbladh;
extern const struct GameDriver driver_lastsold;
extern const struct GameDriver driver_shocktroa;
extern const struct GameDriver driver_rbff2h;
extern const struct GameDriver driver_rbff2k;
extern const struct GameDriver driver_mslug2t;
extern const struct GameDriver driver_vliner7e;
extern const struct GameDriver driver_vliner6e;
extern const struct GameDriver driver_vliner54;
extern const struct GameDriver driver_vliner53;
extern const struct GameDriver driver_kof97pls;

const struct GameDriver *drivers[] = {
	&driver_pacman,
	&driver_pacmanjp,
	&driver_pacmanm,
	&driver_npacmod,
	&driver_pacmod,
	&driver_hangly,
	&driver_hangly2,
	&driver_puckman,
	&driver_pacheart,
	&driver_piranha,
	&driver_pacplus,
	&driver_mspacman,
	&driver_mspacatk,
	&driver_pacgal,
	&driver_crush,
	&driver_crush2,
	&driver_crush3,
	&driver_maketrax,
	&driver_mbrush,
	&driver_paintrlr,
	&driver_ponpoko,
	&driver_ponpokov,
	&driver_eyes,
	&driver_eyes2,
	&driver_mrtnt,
	&driver_lizwiz,
	&driver_theglob,
	&driver_beastf,
	&driver_dremshpr,
	&driver_vanvan,
	&driver_vanvans,
	&driver_alibaba,
	&driver_circus,
	&driver_robotbwl,
	&driver_crash,
	&driver_ripcord,
	&driver_sidetrac,
	&driver_targ,
	&driver_spectar,
	&driver_spectar1,
	&driver_mtrap,
	&driver_mtrap3,
	&driver_mtrap4,
	&driver_venture,
	&driver_venture2,
	&driver_venture4,
	&driver_pepper2,
	&driver_hardhat,
	&driver_fax,
	&driver_seawolf2,
	&driver_spacezap,
	&driver_ebases,
	&driver_wow,
	&driver_gorf,
	&driver_gorfpgm1,
	&driver_robby,
	&driver_profpac,
	&driver_starfire,
	&driver_fireone,
	&driver_victory,
	&driver_victorba,
	&driver_1942,
	&driver_1942a,
	&driver_1942b,
	&driver_1943,
	&driver_1943e,
	&driver_1943j,
	&driver_1943kai,
	&driver_galaga,
	&driver_galagamw,
	&driver_galagads,
	&driver_gallag,
	&driver_galagab2,
	&driver_galaga84,
	&driver_nebulbee,
	&driver_radarscp,
	&driver_dkong,
	&driver_dkongjp,
	&driver_dkongjpo,
	&driver_dkongjr,
	&driver_dkngjrjp,
	&driver_dkjrjp,
	&driver_dkjrbl,
	&driver_dkong3,
	&driver_dkong3j,
	&driver_hunchbkd,
	&driver_herbiedk,
	&driver_herocast,
	&driver_galaxian,
	&driver_galmidw,
	&driver_superg,
	&driver_galaxb,
	&driver_galapx,
	&driver_galap1,
	&driver_galap4,
	&driver_galturbo,
	&driver_swarm,
	&driver_zerotime,
	&driver_uniwars,
	&driver_gteikoku,
	&driver_spacbatt,
	&driver_warofbug,
	&driver_pacmanbl,
	&driver_devilfsg,
	&driver_zigzag,
	&driver_zigzag2,
	&driver_scramblb,
	&driver_jumpbug,
	&driver_jumpbugb,
	&driver_levers,
	&driver_azurian,
	&driver_checkman,
	&driver_checkmaj,
	&driver_streakng,
	&driver_mooncrst,
	&driver_mooncrsg,
	&driver_mooncrsb,
	&driver_mooncrs2,
	&driver_fantazia,
	&driver_eagle,
	&driver_eagle2,
	&driver_mooncrgx,
	&driver_moonqsr,
	&driver_moonal2,
	&driver_moonal2b,
	&driver_kingball,
	&driver_kingbalj,
	&driver_frogger,
	&driver_frogseg1,
	&driver_frogseg2,
	&driver_froggrmc,
	&driver_scramble,
	&driver_scrambls,
	&driver_atlantis,
	&driver_atlants2,
	&driver_theend,
	&driver_theends,
	&driver_froggers,
	&driver_amidars,
	&driver_triplep,
	&driver_knockout,
	&driver_mariner,
	&driver_800fath,
	&driver_ckongs,
	&driver_mars,
	&driver_devilfsh,
	&driver_newsin7,
	&driver_hotshock,
	&driver_hunchbks,
	&driver_pspikes,
	&driver_svolly91,
	&driver_karatblz,
	&driver_karatblu,
	&driver_spinlbrk,
	&driver_spinlbru,
	&driver_spinlbrj,
	&driver_turbofrc,
	&driver_aerofgt,
	&driver_aerofgtb,
	&driver_aerofgtc,
	&driver_sonicwi,
	&driver_bloodbro,
	&driver_weststry,
	&driver_neogeo,
	&driver_nam1975,
	&driver_bstars,
	&driver_tpgolf,
	&driver_mahretsu,
	&driver_ridhero,
	&driver_alpham2,
	&driver_cyberlip,
	&driver_superspy,
	&driver_mutnat,
	&driver_kotm,
	&driver_sengoku,
	&driver_sengokh,
	&driver_burningf,
	&driver_burningh,
	&driver_lbowling,
	&driver_gpilots,
	&driver_joyjoy,
	&driver_quizdais,
	&driver_lresort,
	&driver_eightman,
	&driver_legendos,
	&driver_2020bb,
	&driver_2020bbh,
	&driver_socbrawl,
	&driver_fatfury1,
	&driver_roboarmy,
	&driver_fbfrenzy,
	&driver_kotm2,
	&driver_sengoku2,
	&driver_bstars2,
	&driver_quizdai2,
	&driver_3countb,
	&driver_aof,
	&driver_samsho,
	&driver_tophuntr,
	&driver_fatfury2,
	&driver_ssideki,
	&driver_kof94,
	&driver_aof2,
	&driver_fatfursp,
	&driver_savagere,
	&driver_ssideki2,
	&driver_samsho2,
	&driver_fatfury3,
	&driver_ssideki3,
	&driver_kof95,
	&driver_samsho3,
	&driver_rbff1,
	&driver_aof3,
	&driver_kof96,
	&driver_ssideki4,
	&driver_kizuna,
	&driver_samsho4,
	&driver_rbffspec,
	&driver_kof97,
	&driver_lastblad,
	&driver_irrmaze,
	&driver_rbff2,
	&driver_mslug2,
	&driver_kof98,
	&driver_lastbld2,
	&driver_neocup98,
	&driver_mslugx,
	&driver_kof99,
	&driver_garou,
	&driver_maglord,
	&driver_maglordh,
	&driver_ncombat,
	&driver_bjourney,
	&driver_crsword,
	&driver_trally,
	&driver_ncommand,
	&driver_wh1,
	&driver_wh2,
	&driver_wh2j,
	&driver_aodk,
	&driver_whp,
	&driver_mosyougi,
	&driver_overtop,
	&driver_ninjamas,
	&driver_twinspri,
	&driver_janshin,
	&driver_pulstar,
	&driver_spinmast,
	&driver_wjammers,
	&driver_karnovr,
	&driver_strhoop,
	&driver_magdrop2,
	&driver_magdrop3,
	&driver_gururin,
	&driver_miexchng,
	&driver_panicbom,
	&driver_kabukikl,
	&driver_neobombe,
	&driver_minasan,
	&driver_bakatono,
	&driver_turfmast,
	&driver_mslug,
	&driver_zedblade,
	&driver_viewpoin,
	&driver_quizkof,
	&driver_stakwin,
	&driver_ragnagrd,
	&driver_pgoal,
	&driver_stakwin2,
	&driver_shocktro,
	&driver_shocktr2,
	&driver_galaxyfg,
	&driver_wakuwak7,
	&driver_pbobble,
	&driver_pbobbl2n,
	&driver_marukodq,
	&driver_doubledr,
	&driver_gowcaizr,
	&driver_sdodgeb,
	&driver_tws96,
	&driver_blazstar,
	&driver_fightfev,
	&driver_pspikes2,
	&driver_sonicwi2,
	&driver_sonicwi3,
	&driver_popbounc,
	&driver_androdun,
	&driver_puzzledp,
	&driver_neomrdo,
	&driver_goalx3,
	&driver_neodrift,
	&driver_breakers,
	&driver_puzzldpr,
	&driver_breakrev,
	&driver_flipshot,
	&driver_ctomaday,
	&driver_nam1975m,
	&driver_bstarsm,
	&driver_tpgolfm,
	&driver_mahretsum,
	&driver_maglordm,
	&driver_alpham2m,
	&driver_ncombatm,
	&driver_cyberlipm,
	&driver_superspym,
	&driver_mutnatm,
	&driver_kotmm,
	&driver_sengokum,
	&driver_burningfm,
	&driver_lbowlingm,
	&driver_gpilotsm,
	&driver_joyjoym,
	&driver_bjourneym,
	&driver_quizdaism,
	&driver_lresortm,
	&driver_eightmanm,
	&driver_legendosm,
	&driver_2020bbm,
	&driver_socbrawlm,
	&driver_roboarmym,
	&driver_fatfury1m,
	&driver_fbfrenzym,
	&driver_crswordm,
	&driver_trallym,
	&driver_bstars2m,
	&driver_quizdai2m,
	&driver_samshom,
	&driver_tophuntrm,
	&driver_androdunm,
	&driver_ncommandm,
	&driver_kof94m,
	&driver_aof2m,
	&driver_wh2m,
	&driver_fatfurspm,
	&driver_savagerem,
	&driver_fightfevm,
	&driver_ssideki2m,
	&driver_spinmastm,
	&driver_samsho2m,
	&driver_wh2jm,
	&driver_wjammersm,
	&driver_karnovrm,
	&driver_gururinm,
	&driver_pspikes2m,
	&driver_fatfury3m,
	&driver_b2b,
	&driver_panicbomm,
	&driver_aodkm,
	&driver_sonicwi2m,
	&driver_zedbladem,
	&driver_galaxyfgm,
	&driver_strhoopm,
	&driver_quizkofm,
	&driver_ssideki3m,
	&driver_doubledrm,
	&driver_kof95m,
	&driver_twsoc96,
	&driver_samsho3m,
	&driver_stakwinm,
	&driver_pulstarm,
	&driver_whpm,
	&driver_kabukiklm,
	&driver_neobombem,
	&driver_gowcaizrm,
	&driver_rbff1m,
	&driver_aof3m,
	&driver_sonicwi3m,
	&driver_turfmastm,
	&driver_mslugm,
	&driver_puzzledpm,
	&driver_moshougi,
	&driver_marukodqm,
	&driver_neomrdom,
	&driver_sdodgebm,
	&driver_goalx3m,
	&driver_overtopm,
	&driver_neodriftm,
	&driver_kof96m,
	&driver_ssideki4m,
	&driver_kizunam,
	&driver_ninjamasm,
	&driver_ragnagrdm,
	&driver_pgoalm,
	&driver_ironclad,
	&driver_magdrop2m,
	&driver_samsho4m,
	&driver_rbffspecm,
	&driver_twinsprim,
	&driver_wakuwak7m,
	&driver_stakwin2m,
	&driver_ghostlop,
	&driver_breakersm,
	&driver_miexchngm,
	&driver_kof97m,
	&driver_magdrop3m,
	&driver_lastbladm,
	&driver_puzzldprm,
	&driver_popbouncm,
	&driver_shocktrom,
	&driver_blazstarm,
	&driver_rbff2m,
	&driver_mslug2m,
	&driver_lastbld2m,
	&driver_neocup98m,
	&driver_breakrevm,
	&driver_shocktr2m,
	&driver_flipshotm,
	&driver_pbobbl2nm,
	&driver_ctomadaym,
	&driver_mslugxm,
	&driver_vliner,
	&driver_zintrckb,
	&driver_froman2b,
	&driver_crswd2bl,
	&driver_diggerma,
	&driver_lasthope,
	&driver_bstarsh,
	&driver_maglordhm,
	&driver_ncombath,
	&driver_kotmh,
	&driver_sengokuh,
	&driver_burningfh,
	&driver_gpilotsh,
	&driver_bjourneyh,
	&driver_quizdaisk,
	&driver_2020bba,
	&driver_socbrawlh,
	&driver_samshoh,
	&driver_tophuntrh,
	&driver_aof2a,
	&driver_wh2h,
	&driver_fatfurspa,
	&driver_fightfeva,
	&driver_samsho2k,
	&driver_samsho2ka,
	&driver_quizkofk,
	&driver_kof95a,
	&driver_kof95h,
	&driver_samsho3h,
	&driver_fswords,
	&driver_rbff1a,
	&driver_rbff1ka,
	&driver_rbff1k,
	&driver_aof3k,
	&driver_kof96a,
	&driver_kof96h,
	&driver_ironclado,
	&driver_samsho4k,
	&driver_rbffspeck,
	&driver_kof97h,
	&driver_kof97k,
	&driver_lastbladh,
	&driver_lastsold,
	&driver_shocktroa,
	&driver_rbff2h,
	&driver_rbff2k,
	&driver_mslug2t,
	&driver_vliner7e,
	&driver_vliner6e,
	&driver_vliner54,
	&driver_vliner53,
	&driver_kof97pls,
	0
};
