/* Generated by gen_drivers.py from: src/drivers/pacman.c src/drivers/circus.c src/drivers/exidy.c src/drivers/astrocde.c src/drivers/starfire.c src/drivers/victory.c src/drivers/1942.c src/drivers/1943.c src/drivers/galaga.c src/drivers/dkong.c src/drivers/galaxian.c src/drivers/frogger.c src/drivers/scramble.c src/drivers/aerofgt.c src/drivers/bloodbro.c */
#include "driver.h"

struct GameDriver driver_0 = { __FILE__, 0, "", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };

struct GameDriver driver_amidar = { __FILE__, 0, "amidar", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };
struct GameDriver driver_ckong = { __FILE__, 0, "ckong", 0, 0, 0, 0, 0, 0, 0, NOT_A_DRIVER };

extern const struct GameDriver driver_pacman;
extern const struct GameDriver driver_pacmanjp;
extern const struct GameDriver driver_pacmanm;
extern const struct GameDriver driver_npacmod;
extern const struct GameDriver driver_pacmod;
extern const struct GameDriver driver_hangly;
extern const struct GameDriver driver_hangly2;
extern const struct GameDriver driver_puckman;
extern const struct GameDriver driver_pacheart;
extern const struct GameDriver driver_piranha;
extern const struct GameDriver driver_pacplus;
extern const struct GameDriver driver_mspacman;
extern const struct GameDriver driver_mspacatk;
extern const struct GameDriver driver_pacgal;
extern const struct GameDriver driver_crush;
extern const struct GameDriver driver_crush2;
extern const struct GameDriver driver_crush3;
extern const struct GameDriver driver_maketrax;
extern const struct GameDriver driver_mbrush;
extern const struct GameDriver driver_paintrlr;
extern const struct GameDriver driver_ponpoko;
extern const struct GameDriver driver_ponpokov;
extern const struct GameDriver driver_eyes;
extern const struct GameDriver driver_eyes2;
extern const struct GameDriver driver_mrtnt;
extern const struct GameDriver driver_lizwiz;
extern const struct GameDriver driver_theglob;
extern const struct GameDriver driver_beastf;
extern const struct GameDriver driver_dremshpr;
extern const struct GameDriver driver_vanvan;
extern const struct GameDriver driver_vanvans;
extern const struct GameDriver driver_alibaba;
extern const struct GameDriver driver_circus;
extern const struct GameDriver driver_robotbwl;
extern const struct GameDriver driver_crash;
extern const struct GameDriver driver_ripcord;
extern const struct GameDriver driver_sidetrac;
extern const struct GameDriver driver_targ;
extern const struct GameDriver driver_spectar;
extern const struct GameDriver driver_spectar1;
extern const struct GameDriver driver_mtrap;
extern const struct GameDriver driver_mtrap3;
extern const struct GameDriver driver_mtrap4;
extern const struct GameDriver driver_venture;
extern const struct GameDriver driver_venture2;
extern const struct GameDriver driver_venture4;
extern const struct GameDriver driver_pepper2;
extern const struct GameDriver driver_hardhat;
extern const struct GameDriver driver_fax;
extern const struct GameDriver driver_seawolf2;
extern const struct GameDriver driver_spacezap;
extern const struct GameDriver driver_ebases;
extern const struct GameDriver driver_wow;
extern const struct GameDriver driver_gorf;
extern const struct GameDriver driver_gorfpgm1;
extern const struct GameDriver driver_robby;
extern const struct GameDriver driver_profpac;
extern const struct GameDriver driver_starfire;
extern const struct GameDriver driver_fireone;
extern const struct GameDriver driver_victory;
extern const struct GameDriver driver_victorba;
extern const struct GameDriver driver_1942;
extern const struct GameDriver driver_1942a;
extern const struct GameDriver driver_1942b;
extern const struct GameDriver driver_1943;
extern const struct GameDriver driver_1943e;
extern const struct GameDriver driver_1943j;
extern const struct GameDriver driver_1943kai;
extern const struct GameDriver driver_galaga;
extern const struct GameDriver driver_galagamw;
extern const struct GameDriver driver_galagads;
extern const struct GameDriver driver_gallag;
extern const struct GameDriver driver_galagab2;
extern const struct GameDriver driver_galaga84;
extern const struct GameDriver driver_nebulbee;
extern const struct GameDriver driver_radarscp;
extern const struct GameDriver driver_dkong;
extern const struct GameDriver driver_dkongjp;
extern const struct GameDriver driver_dkongjpo;
extern const struct GameDriver driver_dkongjr;
extern const struct GameDriver driver_dkngjrjp;
extern const struct GameDriver driver_dkjrjp;
extern const struct GameDriver driver_dkjrbl;
extern const struct GameDriver driver_dkong3;
extern const struct GameDriver driver_dkong3j;
extern const struct GameDriver driver_hunchbkd;
extern const struct GameDriver driver_herbiedk;
extern const struct GameDriver driver_herocast;
extern const struct GameDriver driver_galaxian;
extern const struct GameDriver driver_galmidw;
extern const struct GameDriver driver_superg;
extern const struct GameDriver driver_galaxb;
extern const struct GameDriver driver_galapx;
extern const struct GameDriver driver_galap1;
extern const struct GameDriver driver_galap4;
extern const struct GameDriver driver_galturbo;
extern const struct GameDriver driver_swarm;
extern const struct GameDriver driver_zerotime;
extern const struct GameDriver driver_uniwars;
extern const struct GameDriver driver_gteikoku;
extern const struct GameDriver driver_spacbatt;
extern const struct GameDriver driver_warofbug;
extern const struct GameDriver driver_pacmanbl;
extern const struct GameDriver driver_devilfsg;
extern const struct GameDriver driver_zigzag;
extern const struct GameDriver driver_zigzag2;
extern const struct GameDriver driver_scramblb;
extern const struct GameDriver driver_jumpbug;
extern const struct GameDriver driver_jumpbugb;
extern const struct GameDriver driver_levers;
extern const struct GameDriver driver_azurian;
extern const struct GameDriver driver_checkman;
extern const struct GameDriver driver_checkmaj;
extern const struct GameDriver driver_streakng;
extern const struct GameDriver driver_mooncrst;
extern const struct GameDriver driver_mooncrsg;
extern const struct GameDriver driver_mooncrsb;
extern const struct GameDriver driver_mooncrs2;
extern const struct GameDriver driver_fantazia;
extern const struct GameDriver driver_eagle;
extern const struct GameDriver driver_eagle2;
extern const struct GameDriver driver_mooncrgx;
extern const struct GameDriver driver_moonqsr;
extern const struct GameDriver driver_moonal2;
extern const struct GameDriver driver_moonal2b;
extern const struct GameDriver driver_kingball;
extern const struct GameDriver driver_kingbalj;
extern const struct GameDriver driver_frogger;
extern const struct GameDriver driver_frogseg1;
extern const struct GameDriver driver_frogseg2;
extern const struct GameDriver driver_froggrmc;
extern const struct GameDriver driver_scramble;
extern const struct GameDriver driver_scrambls;
extern const struct GameDriver driver_atlantis;
extern const struct GameDriver driver_atlants2;
extern const struct GameDriver driver_theend;
extern const struct GameDriver driver_theends;
extern const struct GameDriver driver_froggers;
extern const struct GameDriver driver_amidars;
extern const struct GameDriver driver_triplep;
extern const struct GameDriver driver_knockout;
extern const struct GameDriver driver_mariner;
extern const struct GameDriver driver_800fath;
extern const struct GameDriver driver_ckongs;
extern const struct GameDriver driver_mars;
extern const struct GameDriver driver_devilfsh;
extern const struct GameDriver driver_newsin7;
extern const struct GameDriver driver_hotshock;
extern const struct GameDriver driver_hunchbks;
extern const struct GameDriver driver_pspikes;
extern const struct GameDriver driver_svolly91;
extern const struct GameDriver driver_karatblz;
extern const struct GameDriver driver_karatblu;
extern const struct GameDriver driver_spinlbrk;
extern const struct GameDriver driver_spinlbru;
extern const struct GameDriver driver_spinlbrj;
extern const struct GameDriver driver_turbofrc;
extern const struct GameDriver driver_aerofgt;
extern const struct GameDriver driver_aerofgtb;
extern const struct GameDriver driver_aerofgtc;
extern const struct GameDriver driver_sonicwi;
extern const struct GameDriver driver_bloodbro;
extern const struct GameDriver driver_weststry;

const struct GameDriver *drivers[] = {
	&driver_pacman,
	&driver_pacmanjp,
	&driver_pacmanm,
	&driver_npacmod,
	&driver_pacmod,
	&driver_hangly,
	&driver_hangly2,
	&driver_puckman,
	&driver_pacheart,
	&driver_piranha,
	&driver_pacplus,
	&driver_mspacman,
	&driver_mspacatk,
	&driver_pacgal,
	&driver_crush,
	&driver_crush2,
	&driver_crush3,
	&driver_maketrax,
	&driver_mbrush,
	&driver_paintrlr,
	&driver_ponpoko,
	&driver_ponpokov,
	&driver_eyes,
	&driver_eyes2,
	&driver_mrtnt,
	&driver_lizwiz,
	&driver_theglob,
	&driver_beastf,
	&driver_dremshpr,
	&driver_vanvan,
	&driver_vanvans,
	&driver_alibaba,
	&driver_circus,
	&driver_robotbwl,
	&driver_crash,
	&driver_ripcord,
	&driver_sidetrac,
	&driver_targ,
	&driver_spectar,
	&driver_spectar1,
	&driver_mtrap,
	&driver_mtrap3,
	&driver_mtrap4,
	&driver_venture,
	&driver_venture2,
	&driver_venture4,
	&driver_pepper2,
	&driver_hardhat,
	&driver_fax,
	&driver_seawolf2,
	&driver_spacezap,
	&driver_ebases,
	&driver_wow,
	&driver_gorf,
	&driver_gorfpgm1,
	&driver_robby,
	&driver_profpac,
	&driver_starfire,
	&driver_fireone,
	&driver_victory,
	&driver_victorba,
	&driver_1942,
	&driver_1942a,
	&driver_1942b,
	&driver_1943,
	&driver_1943e,
	&driver_1943j,
	&driver_1943kai,
	&driver_galaga,
	&driver_galagamw,
	&driver_galagads,
	&driver_gallag,
	&driver_galagab2,
	&driver_galaga84,
	&driver_nebulbee,
	&driver_radarscp,
	&driver_dkong,
	&driver_dkongjp,
	&driver_dkongjpo,
	&driver_dkongjr,
	&driver_dkngjrjp,
	&driver_dkjrjp,
	&driver_dkjrbl,
	&driver_dkong3,
	&driver_dkong3j,
	&driver_hunchbkd,
	&driver_herbiedk,
	&driver_herocast,
	&driver_galaxian,
	&driver_galmidw,
	&driver_superg,
	&driver_galaxb,
	&driver_galapx,
	&driver_galap1,
	&driver_galap4,
	&driver_galturbo,
	&driver_swarm,
	&driver_zerotime,
	&driver_uniwars,
	&driver_gteikoku,
	&driver_spacbatt,
	&driver_warofbug,
	&driver_pacmanbl,
	&driver_devilfsg,
	&driver_zigzag,
	&driver_zigzag2,
	&driver_scramblb,
	&driver_jumpbug,
	&driver_jumpbugb,
	&driver_levers,
	&driver_azurian,
	&driver_checkman,
	&driver_checkmaj,
	&driver_streakng,
	&driver_mooncrst,
	&driver_mooncrsg,
	&driver_mooncrsb,
	&driver_mooncrs2,
	&driver_fantazia,
	&driver_eagle,
	&driver_eagle2,
	&driver_mooncrgx,
	&driver_moonqsr,
	&driver_moonal2,
	&driver_moonal2b,
	&driver_kingball,
	&driver_kingbalj,
	&driver_frogger,
	&driver_frogseg1,
	&driver_frogseg2,
	&driver_froggrmc,
	&driver_scramble,
	&driver_scrambls,
	&driver_atlantis,
	&driver_atlants2,
	&driver_theend,
	&driver_theends,
	&driver_froggers,
	&driver_amidars,
	&driver_triplep,
	&driver_knockout,
	&driver_mariner,
	&driver_800fath,
	&driver_ckongs,
	&driver_mars,
	&driver_devilfsh,
	&driver_newsin7,
	&driver_hotshock,
	&driver_hunchbks,
	&driver_pspikes,
	&driver_svolly91,
	&driver_karatblz,
	&driver_karatblu,
	&driver_spinlbrk,
	&driver_spinlbru,
	&driver_spinlbrj,
	&driver_turbofrc,
	&driver_aerofgt,
	&driver_aerofgtb,
	&driver_aerofgtc,
	&driver_sonicwi,
	&driver_bloodbro,
	&driver_weststry,
	0
};
