// This file is AUTO GENERATED by CMake.
#pragma once
#include <SDL/SDL_video.h>

#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif

#define ROM_PATH RG_BASE_PATH_ROMS "/cannonball"
#define SAVE_PATH RG_BASE_PATH_SAVES "/cannonball"
#define CONFIG_PATH RG_BASE_PATH_CONFIG "/cannonball"

static const char* FILENAME_CONFIG UNUSED = "config.xml";
static const char* FILENAME_SCORES UNUSED = "hiscores.xml";
static const char* FILENAME_SCORES_JAPAN UNUSED = "hiscores_jap.xml";
static const char* FILENAME_TTRIAL UNUSED = "hiscores_timetrial.xml";
static const char* FILENAME_TTRIAL_JAPAN UNUSED = "hiscores_timetrial_jap.xml";
static const char* FILENAME_CONT UNUSED = "hiscores_continuous.xml";
static const char* FILENAME_CONT_JAPAN UNUSED = "hiscores_continuous_jap.xml";
const static int SDL_FLAGS UNUSED = SDL_HWSURFACE||SDL_NOFRAME|SDL_ANYFORMAT;
