#!/usr/bin/env python3
"""Generate emucore/DefPropsCompact.hxx from emucore/DefProps.hxx.

Stella's built-in database has 3250 entries of 21 strings each (540 KB of
flash), but most entries only carry the cartridge name, maker and notes. The
emulation reads only the fields from Cartridge_Sound (6) on: cartridge type,
controllers, TV type, display format and so on. The compact table keeps the
936 entries that set at least one of those, as "index=value;..." strings,
sorted by MD5 so the lookup stays a binary search.

Run from this directory: python3 compact_props.py
"""
import re

FIRST_FUNCTIONAL = 6  # Cartridge_Sound, see emucore/Props.hxx

src = open("emucore/DefProps.hxx", encoding="latin-1").read()
rows = re.findall(r'\{ ((?:"(?:[^"\\]|\\.)*",? ?){21}) ?\}', src)
out = []
for r in rows:
    f = re.findall(r'"((?:[^"\\]|\\.)*)"', r)
    assert len(f) == 21
    kv = [f"{i}={v}" for i, v in enumerate(f) if i >= FIRST_FUNCTIONAL and v]
    for item in kv:
        assert ";" not in item[item.index("=") + 1:], item
    if kv:
        out.append((f[0].lower(), ";".join(kv)))
# DefProps.hxx has one entry out of order (E68E2875..., unreachable by its binary search): sort.
out.sort()

with open("emucore/DefPropsCompact.hxx", "w", encoding="latin-1") as f:
    f.write("// Generated by compact_props.py from DefProps.hxx: do not edit.\n")
    f.write("// Only the entries that change the emulation, fields from Cartridge_Sound on.\n\n")
    f.write("#ifndef DEF_PROPS_COMPACT_HXX\n#define DEF_PROPS_COMPACT_HXX\n\n")
    f.write(f"#define DEF_PROPS_SIZE {len(out)}\n\n")
    f.write("static const struct { const char md5[33]; const char *props; } DefProps[DEF_PROPS_SIZE] = {\n")
    for md5, props in out:
        f.write(f'  {{ "{md5}", "{props}" }},\n')
    f.write("};\n\n#endif\n")
print(f"{len(rows)} entries -> {len(out)} with emulation settings")
